{
  "hash": "54a7f6571fb819398a0de6370b2c6858",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Sesión 9: medias marginales y contrastes\"\nauthor:\n  - Camila Zugarramurdi\n  - Álvaro Cabana\ndate: \"2022\"\nlang: es\n---\n\n\n\n\n# Medias marginales, pruebas pareadas, contrastes, y todo eso.\n\nPor lo general, uno ajusta un modelo (en el mejor de los casos, nuestro diseño nos **dice** qué modelo formular), y mira las pruebas de hipótesis sobre los parámetros. Casi siempre, además, nos interesan los \"efectos\" de las variables, y los de sus interacciones. Generalmente utilizamos para esto último pruebas F o \"ANOVAs\".\n\nPero, como casi siempre tenemos más de una variable predictora, y como mínimo una complejidad de 2x2 en el diseño (dos variables categóricas de dos niveles cada una), nos suele interesar *contrastar* directamente las diferencias entre *pares* de niveles. Las (a veces mal llamadas) comparaciones **post-hoc**. En esta sesión veremos algunas formas de calcular estos contrastes pareados.\n\n## Las medias marginales y el paquete `emmeans`\n\nEl paquete `emmmeans` (antes conocido como) `lsmeans` permite, entre otras cosas, calcular \"medias marginales\", esto es, los promedios de la variable dependiente según diferentes niveles de una o más variables predictoras categóricas.\n\n¿Qué? ¿Que qué cornos quiero decir con esto? Ok, basta de cháchara, pongamos un ejemplo. Eso sí, necesitaremos volver los datos de Valentina Paz *et al* que usamos en el [ejercicio 6](https://eva-cursos.psico.edu.uy/pluginfile.php/144346/mod_resource/content/4/curso-R---ejercicio-6_csol_2022.pdf) y en la [sesión 7](https://eva-cursos.psico.edu.uy/pluginfile.php/144816/mod_resource/content/3/curso-R---sesion-7_2022_ggplot2.pdf). Porque reusar, reciclar, reparar, es un gran mantra. En particular, necesitaremos el data frame largo `parts3` que luce así:\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nstr(parts3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t336 obs. of  6 variables:\n $ codigo     : Factor w/ 112 levels \"v001                \",..: 1 2 3 4 5 6 7 8 9 10 ...\n $ sexo       : Factor w/ 2 levels \"H\",\"M\": 2 1 2 2 2 1 2 2 1 2 ...\n $ edad       : num  22 27 21 21 25 26 20 21 24 31 ...\n $ Beck       : num  2 38 13 8 30 6 13 7 7 21 ...\n $ tipo_oferta: Factor w/ 3 levels \"justas\",\"injustas\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ enojo      : num  0.667 0 0.333 0.833 0.5 ...\n```\n\n\n:::\n:::\n\n\nEn sesiones pasadas vimos cómo usando paquetes como `dplyr` podíamos obtener los promedios para los valores de enojo según, sexo, tipo de oferta, o un para la combinación de los niveles de ambas. Algo así como:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmediasEnojo=parts3 %>% group_by(sexo,tipo_oferta) %>% \n  summarize(mediaEnojo = mean(enojo,na.rm=T))\nmediasEnojo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n# Groups:   sexo [2]\n  sexo  tipo_oferta mediaEnojo\n  <fct> <fct>            <dbl>\n1 H     justas           0.733\n2 H     injustas         4.04 \n3 H     medias           2.29 \n4 M     justas           0.303\n5 M     injustas         4.02 \n6 M     medias           1.81 \n```\n\n\n:::\n:::\n\n\nAhora, ¿qué pasa si quieren **comparar** las medias de, digamos, ofertas justas e injustas, para los participantes hombres? Un ejemplo típico de comparación pareada, que cuando se calcula *a posteriori* (cuando no se \"planifica\" de antemano, o se realiza mansalva todos contra todos, ver más adelante), se suele llamar *post-hoc*.\n\nEn tal caso, podemos utilizar el paquete `emmeans` para calcular estimaciones un poco más \"prolijas\" y menos caseras de las medias. Primero, debemos ajustar un modelo lineal relevante: en este caso, queremos el enojo según sexo y tipo de oferta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenojo.lm1 = lm(enojo~sexo + tipo_oferta,data=parts3)\nsummary(enojo.lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = enojo ~ sexo + tipo_oferta, data = parts3)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.2231 -1.0129 -0.3222  0.9627  4.6537 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           0.6556     0.2182   3.004  0.00287 ** \nsexoM                -0.3090     0.2080  -1.485  0.13838    \ntipo_ofertainjustas   3.5676     0.2446  14.585  < 2e-16 ***\ntipo_ofertamedias     1.5240     0.2446   6.231 1.42e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.822 on 329 degrees of freedom\n  (3 observations deleted due to missingness)\nMultiple R-squared:  0.3968,\tAdjusted R-squared:  0.3913 \nF-statistic: 72.15 on 3 and 329 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nPrimero que nada, calculemos una \"grilla de referencia\" con `ref_grid`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(emmeans)\n# Primer paso, calcular la \"grilla de referencia\". Esto no es siempre necesario, \n# pero es un buen hábito.\nenojo.lm1.rg = ref_grid(enojo.lm1)\n```\n:::\n\n\nLuego, calculemos las medias marginales para la variable `sexo`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenojo.lm1.emm.sexo = emmeans(enojo.lm1.rg,\"sexo\")\n```\n:::\n\n\nHacemos el summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(enojo.lm1.emm.sexo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sexo emmean    SE  df lower.CL upper.CL\n H      2.35 0.166 329     2.03     2.68\n M      2.04 0.125 329     1.80     2.29\n\nResults are averaged over the levels of: tipo_oferta \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nBien! En promedio, los hombres tienen 2.35 de enojo, y las mujeres 2.04. Eso es lo que informa la columna `emmean`. La gracia es que ahora sabemos el error estándar de la estimación, los grados de libertad, y el inervalo de confianza (`lower.CL` y `upper.CL` son los límites inferior y superior del intervalo).\n\nAhora, ¿cómo hago para incluir el \"desglose\" del nivel de enojo según sexo y tipo de oferta?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenojo.lm1.emm.sexo.tipoOferta = emmeans(enojo.lm1.rg,c(\"sexo\",\"tipo_oferta\"))\nsummary(enojo.lm1.emm.sexo.tipoOferta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sexo tipo_oferta emmean    SE  df lower.CL upper.CL\n H    justas       0.656 0.218 329   0.2263    1.085\n M    justas       0.347 0.189 329  -0.0242    0.717\n H    injustas     4.223 0.218 329   3.7939    4.652\n M    injustas     3.914 0.189 329   3.5434    4.285\n H    medias       2.180 0.218 329   1.7503    2.609\n M    medias       1.871 0.189 329   1.4998    2.241\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nComparemos estos resultados a los que dió el `summarize`...\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#según emmeans\nsummary(enojo.lm1.emm.sexo.tipoOferta)[1,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sexo tipo_oferta emmean    SE  df lower.CL upper.CL\n H    justas       0.656 0.218 329    0.226     1.08\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#según ddply\nmediasEnojo[1,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n# Groups:   sexo [1]\n  sexo  tipo_oferta mediaEnojo\n  <fct> <fct>            <dbl>\n1 H     justas           0.733\n```\n\n\n:::\n:::\n\n\nEh... es 0.7333, o es 0.655 ?\n\n*Qué está pasando?* \n\n![WHAT\\'S GOING ON?!](images/4nonblondes.jpeg)\n\n\n## Contrastes\n\nOK, dejemos por un momento esa discrepancia... Sigamos adelante, porque, porqué no? Digamos que nos interesa comparar los niveles de enojo, para cada nivel de oferta, **entre** hombres y mujeres... Una de las tantas formas de hacerlo, es con la función `contrast`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrast(enojo.lm1.emm.sexo.tipoOferta,\"pairwise\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                estimate    SE  df t.ratio p.value\n H justas - M justas        0.309 0.208 329   1.485  0.6739\n H justas - H injustas     -3.568 0.245 329 -14.585  <.0001\n H justas - M injustas     -3.259 0.321 329 -10.149  <.0001\n H justas - H medias       -1.524 0.245 329  -6.231  <.0001\n H justas - M medias       -1.215 0.321 329  -3.784  0.0025\n M justas - H injustas     -3.877 0.321 329 -12.074  <.0001\n M justas - M injustas     -3.568 0.245 329 -14.585  <.0001\n M justas - H medias       -1.833 0.321 329  -5.709  <.0001\n M justas - M medias       -1.524 0.245 329  -6.231  <.0001\n H injustas - M injustas    0.309 0.208 329   1.485  0.6739\n H injustas - H medias      2.044 0.245 329   8.355  <.0001\n H injustas - M medias      2.353 0.321 329   7.327  <.0001\n M injustas - H medias      1.735 0.321 329   5.402  <.0001\n M injustas - M medias      2.044 0.245 329   8.355  <.0001\n H medias - M medias        0.309 0.208 329   1.485  0.6739\n\nP value adjustment: tukey method for comparing a family of 6 estimates \n```\n\n\n:::\n:::\n\n\nBueno, es como mucho no? Esto compara TODO CONTRA TODO (el argumento \"pairwise\" hace que se hagan comparaciones de a pares... más sobre esto pronto). La verdad que no me interesa compara H,medias contra M,injustas...\n\nEntonces, si sólo nos interesa hacer comparaciones entre sexos *según* tipo de oferta, al hacer las medias marginales, podemos especificar en vez de `c(\"sexo\",\"tipo_oferta\")`, especificar sólo `\"sexo\"`, y agregar `\"by=tipo_oferta\"` como otro argumento a `emmeans`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenojo.lm1.emm.sexo.tipoOferta_2 = emmeans(enojo.lm1.rg,\"sexo\",by=\"tipo_oferta\")\ncontrast(enojo.lm1.emm.sexo.tipoOferta_2  ,\"pairwise\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntipo_oferta = justas:\n contrast estimate    SE  df t.ratio p.value\n H - M       0.309 0.208 329   1.485  0.1384\n\ntipo_oferta = injustas:\n contrast estimate    SE  df t.ratio p.value\n H - M       0.309 0.208 329   1.485  0.1384\n\ntipo_oferta = medias:\n contrast estimate    SE  df t.ratio p.value\n H - M       0.309 0.208 329   1.485  0.1384\n```\n\n\n:::\n:::\n\n\nAhora sí! Según, cada tipo de oferta, tengo el contraste entre los sexos. Perfecto.\n\nNo?\n\nDigamos que quiero el contraste inverso, dentro de cada sexo, comparar niveles de enojo entre las ofertas. Fácil, sólo hay que invertir los argumentos del `emmeans`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenojo.lm1.emm.sexo.tipoOferta_2 = emmeans(enojo.lm1.rg,by=\"sexo\",\"tipo_oferta\")\ncontrast(enojo.lm1.emm.sexo.tipoOferta_2  ,\"pairwise\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsexo = H:\n contrast          estimate    SE  df t.ratio p.value\n justas - injustas    -3.57 0.245 329 -14.585  <.0001\n justas - medias      -1.52 0.245 329  -6.231  <.0001\n injustas - medias     2.04 0.245 329   8.355  <.0001\n\nsexo = M:\n contrast          estimate    SE  df t.ratio p.value\n justas - injustas    -3.57 0.245 329 -14.585  <.0001\n justas - medias      -1.52 0.245 329  -6.231  <.0001\n injustas - medias     2.04 0.245 329   8.355  <.0001\n\nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\nExcelente!!!\n\nNo?\n\nPero... todos los contrastes son iguales, no importa el sexo... Y en la otra, los contrastes entre sexos eran los mismos, sin importar el nivel del tipo de oferta..\n\n**WHAT'S GOING ON?!** *Qué está pasando?*\n\n![WHAT'S GOING ON?!](images/234096-4-non-blondes-i-said-hey-what-s-going-on%20(1).jpg)\n\n\n**A VER QUIÉN RESUELVE ESTE ENTUERTO!**\n\n> _Pausa:_ Intenta pensar realmente qué está pasando... tómate tu tiempo. Intenta elaborar al menos una hipótesis, vamos, tú puedes!  Vuelve a explorar el modelo lineal que especificaste, del que derivan todas las comparaciones... Le falta algo? Qué implica el dummy coding que está por detrás? _Tip:_ Prueba reemplazar el ´+´ por un asterisco, en la definición del modelo.\n\n\\newpage \n\n### Comparaciones múltiples\n\nBueno, digamos que tenemos una chorrera de contrastes, como los de hace un momento (nota: se ha corregido lo que andaba mal hasta hace un momento, y los contrastes ahora son diferentes.... claro que no se los muestro aquí :P):\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrast(enojo.lm1.emm.sexo.tipoOferta,\"pairwise\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                estimate    SE  df t.ratio p.value\n H justas - M justas       0.4305 0.361 327   1.193  0.8400\n H justas - H injustas    -3.3042 0.408 327  -8.097  <.0001\n H justas - M injustas    -3.2854 0.361 327  -9.106  <.0001\n H justas - H medias      -1.5542 0.408 327  -3.808  0.0023\n H justas - M medias      -1.0765 0.361 327  -2.984  0.0359\n M justas - H injustas    -3.7347 0.361 327 -10.351  <.0001\n M justas - M injustas    -3.7160 0.306 327 -12.131  <.0001\n M justas - H medias      -1.9847 0.361 327  -5.501  <.0001\n M justas - M medias      -1.5070 0.306 327  -4.920  <.0001\n H injustas - M injustas   0.0187 0.361 327   0.052  1.0000\n H injustas - H medias     1.7500 0.408 327   4.288  0.0003\n H injustas - M medias     2.2276 0.361 327   6.174  <.0001\n M injustas - H medias     1.7313 0.361 327   4.798  <.0001\n M injustas - M medias     2.2089 0.306 327   7.211  <.0001\n H medias - M medias       0.4776 0.361 327   1.324  0.7717\n\nP value adjustment: tukey method for comparing a family of 6 estimates \n```\n\n\n:::\n:::\n\n\nY bueno, esto es una chorrera de p-valores... Una cosa frecuente en esta situación, es hacer correcciones por comparaciones múltiples. Estas correcciones pueden ir desde atacar los p-valores con un martillo (Bonferroni), es decir, multiplicar los p-valores por el número de comparaciones realizadas, a estrategias un tanto menos violentas. Hay muchísimas formas de introducir esta corrección, aquí les dejo la forma en que yo suelo hacerlas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(enojo.lm1.emm.sexo.tipoOferta,adjust=\"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                estimate    SE  df t.ratio p.value\n H justas - M justas       0.4305 0.361 327   1.193  1.0000\n H justas - H injustas    -3.3042 0.408 327  -8.097  <.0001\n H justas - M injustas    -3.2854 0.361 327  -9.106  <.0001\n H justas - H medias      -1.5542 0.408 327  -3.808  0.0025\n H justas - M medias      -1.0765 0.361 327  -2.984  0.0459\n M justas - H injustas    -3.7347 0.361 327 -10.351  <.0001\n M justas - M injustas    -3.7160 0.306 327 -12.131  <.0001\n M justas - H medias      -1.9847 0.361 327  -5.501  <.0001\n M justas - M medias      -1.5070 0.306 327  -4.920  <.0001\n H injustas - M injustas   0.0187 0.361 327   0.052  1.0000\n H injustas - H medias     1.7500 0.408 327   4.288  0.0004\n H injustas - M medias     2.2276 0.361 327   6.174  <.0001\n M injustas - H medias     1.7313 0.361 327   4.798  <.0001\n M injustas - M medias     2.2089 0.306 327   7.211  <.0001\n H medias - M medias       0.4776 0.361 327   1.324  1.0000\n\nP value adjustment: bonferroni method for 15 tests \n```\n\n\n:::\n:::\n\n\nEn lugar de `bonferroni` puede ir `mvt` (prueba t multivariada) ,`holm` (Holm-Bonferroni) y `fdr` (False Discovery Rate, creo que es Benjamini-Hochberg, lean la documentación).\n\n## Contraste de contrastes (tumba de campeones)\n\nHay veces, que más que explorar las diferencias, queremos caracterizarlas, queremos poder saber si dos diferencias, son estadísticamente significativas.\n\nPor ejemplo, la diferencia entre el enojo antes ofertas justas e injustas, es en los hombres de 3.3, y en las mujeres de 3.71. ¿Es esta diferencia significativa?\n\n\n::: {.cell}\n\n```{.r .cell-code}\na=contrast(enojo.lm1.emm.sexo.tipoOferta,\"pairwise\")\na[c(2,7),]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast              estimate    SE  df t.ratio p.value\n H justas - H injustas    -3.30 0.408 327  -8.097  <.0001\n M justas - M injustas    -3.72 0.306 327 -12.131  <.0001\n\nP value adjustment: sidak method for 2 tests \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\na[c(11,14),]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast              estimate    SE  df t.ratio p.value\n H injustas - H medias     1.75 0.408 327   4.288  <.0001\n M injustas - M medias     2.21 0.306 327   7.211  <.0001\n\nP value adjustment: sidak method for 2 tests \n```\n\n\n:::\n:::\n\n\nY la diferencia entre el enojo antes ofertas medias e injustas, es en los hombres de 1.75, y en las mujeres de 2.21. Pero, ¿es esta diferencia significativa?\n\nPara responder a esta pregunta, utilizaremos la función `contrast`, pero con un nuevo argumento. Y para esto, tendremos que volver un minuto al listado de medias marginales (sí, acá ya están corregidos :P).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(enojo.lm1.emm.sexo.tipoOferta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sexo tipo_oferta emmean    SE  df lower.CL upper.CL\n H    justas       0.733 0.289 327    0.166    1.301\n M    justas       0.303 0.217 327   -0.123    0.729\n H    injustas     4.037 0.289 327    3.470    4.605\n M    injustas     4.019 0.217 327    3.593    4.445\n H    medias       2.288 0.289 327    1.720    2.855\n M    medias       1.810 0.217 327    1.384    2.236\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nPrimero que nada, ¿cuál es el contraste que queremos hacer? Digamos que sería la diferencia entre injustas y justas de los hombres, menos la misma diferencia para las mujeres:\n\n[ (H, injustas) - (H, medias) ] - [ (M, injustas) - (M, medias) ]\n\no lo que es igual:\n\n(H, injustas) - (H, medias) - (M, injustas) + (M, medias)\n\nAhora, identifiquemos los números de fila relevantes a nuestra comparación.\n\nfila3 - fila5 - fila4 + fila6\n\nPodemos ahora pasar como parámetro a la función `contrast`, los coeficientes de esta suma y resta (-1 y 1) para cada una de las filas de la tabla anterior. En nuestro caso, el coeficiente para la filas 1 y 2 es 0, y luego son 1, -1 -1 y 1 para las filas 3, 4, 5 y 6. Así queda entonces:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrast(enojo.lm1.emm.sexo.tipoOferta,\n         list(hombresVsMujeresEnInjustasMenosMedias=c(0,0,1,-1,-1,1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                              estimate   SE  df t.ratio p.value\n hombresVsMujeresEnInjustasMenosMedias   -0.459 0.51 327  -0.899  0.3691\n```\n\n\n:::\n:::\n\n\nEste contraste tiene un estimado de -0.46 (recuerden que la resta entre condiciones daba 1.75 para hombres y 2.21 para mujeres). Eso medio que ya lo sabíamos: pero ahora tenmos una prueba t y un p-valor asociado y podemos decirlo: \"no hay diferencias entre los sexos para ese contraste entre injustas y medias\".\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}